### ISSUE TITLE
SVG camelCase tags are being overridden preventing proper display.

### ISSUE THREAD

**Issue by morelup** [whitesoup12/remote-falcon#64]
**Your Show Name:**
Adding your show name helps in reproducing the bug.
rosedrivelights

**Describe the bug:**
SVG camelcase not being maintained.

**To Reproduce:**
Go to https://rosedrivelights.remotefalcon.com/remote-falcon and copy the svg image
Note the defs tag has a child tag lineargradient, this should be linearGradient (based on the value recieved from viewerPageContents)
Past this SVG in the body of a new show and see that the SVG fill works correclty in the WYSWYG view but not in the actual show

**Expected behavior:**
linearGraident tag should not be changed to lineargradient

**Screenshots:**
![image](https://github.com/whitesoup12/remote-falcon/assets/8505256/1846d246-43fe-42d0-857a-fde118671784)
![image](https://github.com/whitesoup12/remote-falcon/assets/8505256/ea8ad184-5128-41f0-a285-6be71ba2db09)

**Desktop (if issue is seen on desktop, otherwise N/A):**
 - OS: windows 11
 - Browser chrome

**Comment by whitesoup12** [comment]
This one might be difficult to solve for. The reason why is because JSX (the tags used in ReactJS), do not support camelCase elements. So when you put `linearGradient`, React is converting it to `lineargradient`, which is what React has to have but unfortunately doesn't work with SVGs. Your workaround here would be to just convert the SVG to PNG (or similar) and either host the image somewhere or use base64 image encoding.

**Comment by whitesoup12** [comment]
Closing as `wontfix` since there is not a solution to this within RF.
